### ISSUE TITLE
CJS support dropped in v2

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [omnidan/node-emoji#133]
I think this was unintended, but when I try to `npm i node-emoji@2.0.2` and then `require('node-emoji')` in a file:

```plaintext
/Users/josh/repos/temp/node_modules/node-emoji/lib/index.cjs:46
var import_is2 = __toESM(require("@sindresorhus/is"), 1);
                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/josh/repos/temp/node_modules/@sindresorhus/is/dist/index.js from /Users/josh/repos/temp/node_modules/node-emoji/lib/index.cjs not supported.
Instead change the require of index.js in /Users/josh/repos/temp/node_modules/node-emoji/lib/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/josh/repos/temp/node_modules/node-emoji/lib/index.cjs:46:26)
    at Object.<anonymous> (/Users/josh/repos/temp/index.js:1:21) {
  code: 'ERR_REQUIRE_ESM'
}
```

Copying from https://github.com/omnidan/node-emoji/pull/128#discussion_r1194449591:

> @omnidan I'd kept these at the lower ranges in #113 and #124 because the larger numbers don't work for CJS environments. `@swc/jest` is acting like that. Was it intentional to bump them up?

**Comment by JoshuaKGoldberg** [comment]
Resolved by #128 ✅
